### ISSUE TITLE
Add dog icon for Goblin

### ISSUE THREAD

**Issue by andresn** [imbrianj/switchBoard#60]
:)

http://screencast.com/t/fhaSItbuhFF

**Comment by imbrianj** [comment]
That gh-pages demo is pretty old.  That was simply made to demonstrate that you can change the icon for any given device.  This is how I have it currently (removed the other human's name for privacy reasons):
![temp](https://cloud.githubusercontent.com/assets/526531/14764005/e265c694-095c-11e6-8688-2fa666e70281.png)

I just need to update the gh-pages, but it's kind of a pain to do since I have to rip out a bunch of the code to run websocket connections, polling and anonymize it.
