### ISSUE TITLE
AI Details?

### ISSUE THREAD

**Issue by b3tts32** [imbrianj/switchBoard#69]
I've been parsing through your code trying to understand how you're building models and making predictions. Do you have a breakdown of how it works? I did find a reddit post as well as a few of the guides from your website that gave high level detail. I would like to adapt what you've done with that to store detail in a DB and use with HomeAssistant. Any pointers are greatly appreciated!

**Comment by imbrianj** [comment]
@b3tts32 sorry for the insanely late reply!  I somehow overlooked this and everything has been very busy for me.

When an event is triggered - whether it be a state update or an action (such as turning on a light) - there's a one minute delay allowing for correcting a bad action (AI doing something we didn't want), then it's routed through a delegator: something that can inspect that action and the entirety of the current system state.  This is handy for conditional apps (fire "close blinds" - but the delegator can interrupt this via an app that can see that a window is open).

This delegator also indexes the number of times a given action has occurred on a given device within a given time category [https://github.com/imbrianj/switchBoard/blob/master/lib/ai.js#L197].  Seeing that your bedroom light turns on when motion is detected is nice at 5pm.  Not nice at 5am.  The key structure is: `PROCESSED[category][deviceId][command]` - category being the time in format of `Sun-22` for Sunday, 10pm, for example [https://github.com/imbrianj/switchBoard/blob/master/lib/ai.js#L119].

The value assigned to the key described in the above paragraph is an object of every single device state in the system.  We simply increment a number here - if you had 5, now you have 6.  This happens for eeeevery device and subdevice in the entire system upon every single action.  Trigger a motion sensor in the garage?  This is going to run through the whole system and save the current "state of the world" with every single action.

So we build up a giant has table of simple integers of each state for every device for every event type within each event category.  Once a day [https://github.com/imbrianj/switchBoard/blob/master/lib/db.js#L101], it'll `processFiles` - taking the stored sum of all days and combine with the days sums.  So if `PROCESSED['Sun-22']['Office Lamp']['on']` was 500 since the start of time - and today it had two additional, it'll write 502 to that hash and save to file.  Similarly, it'll do the same for `off` state.

Now we have a simple lookup table with every time category with every device and every device with every state it's had and in what numbers.  When a new event is triggered, we easily calculate the time category using the same time category function, we are given the device name and we can find every device that has reacted to similar events.  We can see the number of times a lamp was "on" and "off".  We can specify to have no action occur if the sample set is too small (1 "on" event and 2 "off" events isn't very confidence inspiring).  Once we have a number events we're happy with (15 by default), we can then look at confidence levels.  By default, we need to be 85% confident that the action should occur.  If the light was on 86 times but off 14, that's enough that we can then fire an intent to execute an "on" command.  If it's 84 times on and 16 times off, it fails to meet the confidence level and the action is ignored.

Hope this helps.  If you have any questions, please let me know.  And again, I apologize for the lateness of this reply.

**Comment by imbrianj** [comment]
Closing this as an issue - if you have further questions, let me know and I'm happy to accommodate.
